apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-kub-demo
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-kub-demo
  template:
    metadata:
      labels:
        app: docker-kub-demo
    spec:
      containers:
        - name: app
          image: docker-kub-demo:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/userdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: sai2714@sql

